# Generated by Django 5.0.4 on 2024-04-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
